// Package init creates an initial EnvDoctor contract from existing repository
// configuration. It is an adoption assistant, not an oracle: it discovers
// variable names only. It never copies environment values, never classifies a
// variable as secret, and never infers authoritative types, requiredness, or
// defaults. Every discovered variable is emitted as an optional string, which
// is the neutral type that makes the draft safe to review and edit.
package init

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/haneefojay/envdoctor/internal/source"
)

// Discovery sources, in preference order. .env.example is preferred because it
// is the canonical declaration of expected variables and normally carries no
// sensitive values.
const (
	EnvExampleFile = ".env.example"
	EnvFile        = ".env"
)

// schemaURI is the only contract version EnvDoctor accepts.
const schemaURI = "https://json-schema.org/draft/2020-12/schema"

// Discover returns the sorted, deduplicated variable names found in the first
// available discovery source in dir. Only names are returned; values are
// discarded by construction and never cross the package boundary. A file that
// exists but cannot be parsed is an error, never a silent skip to the next
// source.
func Discover(dir string) (names []string, sourceFile string, err error) {
	for _, file := range []string{EnvExampleFile, EnvFile} {
		env, rerr := source.LoadDotenv(filepath.Join(dir, file))
		if rerr != nil {
			if os.IsNotExist(rerr) {
				continue
			}
			return nil, file, fmt.Errorf("cannot read %s: %w", file, rerr)
		}
		return namesOf(env), file, nil
	}
	return nil, "", fmt.Errorf("no discovery source found (looked for %s and %s)", EnvExampleFile, EnvFile)
}

// namesOf collects sorted, deduplicated keys from an environment.
func namesOf(env source.Environment) []string {
	names := make([]string, 0, len(env))
	seen := make(map[string]bool, len(env))
	for name := range env {
		if seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// Template renders the initial contract JSON for the discovered names. Every
// variable is declared an optional string. The root description marks the
// output as an advisory draft so it stays distinguishable from authoritative
// contract data. encoding/json serializes the properties map in sorted key
// order, so the output is deterministic.
func Template(names []string) ([]byte, error) {
	properties := make(map[string]map[string]string, len(names))
	for _, name := range names {
		properties[name] = map[string]string{"type": "string"}
	}
	doc := struct {
		Schema      string                       `json:"$schema"`
		Type        string                       `json:"type"`
		Description string                       `json:"description"`
		Properties  map[string]map[string]string `json:"properties"`
	}{
		Schema:      schemaURI,
		Type:        "object",
		Description: "Initial draft generated by envdoctor init. All variables are declared as optional strings and require review before use.",
		Properties:  properties,
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// WriteSchema writes the initial contract to path without overwriting an
// existing file. The non-overwrite check is atomic (O_EXCL), so an existing
// contract is never silently replaced.
func WriteSchema(path string, content []byte) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	if _, err := f.Write(content); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}
