package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net/mail"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

const schemaURL = "https://json-schema.org/draft/2020-12/schema"
const contractVersion = "1"
var integerRE = regexp.MustCompile(`^[+-]?[0-9]+$`)
var numberRE = regexp.MustCompile(`^[+-]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)$`)

type Variable struct {
	Name, Type, Description, Format string
	Required, Secret, HasDefault bool
	Default any
	Enum []any
	Pattern *regexp.Regexp
	MinLength, MaxLength *int
	Minimum, Maximum, ExclusiveMinimum, ExclusiveMaximum, MultipleOf *float64
}
type Contract struct{ Variables map[string]Variable }
type Diagnostic struct{ Severity string `json:"severity"`; Code string `json:"code"`; Variable string `json:"variable"`; Message string `json:"message"` }
type result struct{ Valid bool `json:"valid"`; Diagnostics []Diagnostic `json:"diagnostics"` }

const usage = `EnvDoctor - configuration contract validation

Usage:
  envdoctor init [--contract PATH]
  envdoctor check [--contract PATH] [--env-file PATH | --environment] [--json]
  envdoctor generate example [--contract PATH] [--output PATH] [--force]
`

func main(){os.Exit(run(os.Args[1:],os.Stdout,os.Stderr))}
func run(args []string,out,errOut io.Writer)int{if len(args)==0||args[0]=="-h"||args[0]=="--help"{_,_=io.WriteString(out,usage);return 0};switch args[0]{case "init":return initCommand(args[1:],out,errOut);case "check":return checkCommand(args[1:],out,errOut);case "generate":if len(args)<2||args[1]!="example"{return usageError(errOut)};return generateCommand(args[2:],out,errOut);default:return usageError(errOut)}}

func loadContract(path string)(Contract,error){data,err:=os.ReadFile(path);if err!=nil{return Contract{},fmt.Errorf("read contract: %w",err)};var root map[string]json.RawMessage;d:=json.NewDecoder(bytes.NewReader(data));if err=d.Decode(&root);err!=nil||root==nil{return Contract{},errors.New("contract is not valid JSON")};var extra any;if err=d.Decode(&extra);err!=io.EOF{return Contract{},errors.New("contract contains trailing JSON")};var schema,version,rootType string;if err=json.Unmarshal(root["$schema"],&schema);err!=nil||schema!=schemaURL{return Contract{},errors.New("contract must declare JSON Schema Draft 2020-12")};if err=json.Unmarshal(root["x-envdoctor-version"],&version);err!=nil||version!=contractVersion{return Contract{},errors.New("contract declares an unsupported EnvDoctor version")};if err=json.Unmarshal(root["type"],&rootType);err!=nil||rootType!="object"{return Contract{},errors.New("contract root type must be object")};var props map[string]json.RawMessage;if err=json.Unmarshal(root["properties"],&props);err!=nil||props==nil{return Contract{},errors.New("contract properties must be an object")};var required []string;if raw,ok:=root["required"];ok{if err=json.Unmarshal(raw,&required);err!=nil{return Contract{},errors.New("required must be an array")}};need:=map[string]bool{};for _,name:=range required{if need[name]{return Contract{},fmt.Errorf("CONTRACT_DUPLICATE_VARIABLE: %s",name)};need[name]=true};c:=Contract{Variables:map[string]Variable{}};for name,raw:=range props{v,e:=parseVariable(name,raw);if e!=nil{return Contract{},e};v.Required=need[name];c.Variables[name]=v};for name:=range need{if _,ok:=c.Variables[name];!ok{return Contract{},fmt.Errorf("required variable %s is not declared",name)}};return c,nil}

func parseVariable(name string,raw json.RawMessage)(Variable,error){var object map[string]json.RawMessage;if err:=json.Unmarshal(raw,&object);err!=nil||object==nil{return Variable{},fmt.Errorf("%s definition must be an object",name)};var typ string;if err:=json.Unmarshal(object["type"],&typ);err!=nil||!map[string]bool{"string":true,"integer":true,"number":true,"boolean":true}[typ]{return Variable{},fmt.Errorf("%s must declare a supported type",name)};v:=Variable{Name:name,Type:typ};if raw,ok:=object["description"];ok{if err:=json.Unmarshal(raw,&v.Description);err!=nil{return Variable{},fmt.Errorf("%s description must be a string",name)}};if raw,ok:=object["format"];ok{if err:=json.Unmarshal(raw,&v.Format);err!=nil||(v.Format!=""&&v.Format!="email"&&v.Format!="uri"){return Variable{},fmt.Errorf("%s format is unsupported",name)}};if v.Format!=""&&typ!="string"{return Variable{},fmt.Errorf("%s format requires string type",name)};if raw,ok:=object["x-envdoctor-secret"];ok{if err:=json.Unmarshal(raw,&v.Secret);err!=nil{return Variable{},fmt.Errorf("%s secret marker must be boolean",name)}};if raw,ok:=object["pattern"];ok{var pattern string;if err:=json.Unmarshal(raw,&pattern);err!=nil{return Variable{},fmt.Errorf("%s pattern is invalid",name)};v.Pattern,_=regexp.Compile(pattern)};var err error;v.MinLength,err=intConstraint(object,"minLength");if err!=nil{return Variable{},err};v.MaxLength,err=intConstraint(object,"maxLength");if err!=nil{return Variable{},err};v.Minimum,err=numberConstraint(object,"minimum");if err!=nil{return Variable{},err};v.Maximum,err=numberConstraint(object,"maximum");if err!=nil{return Variable{},err};v.ExclusiveMinimum,err=numberConstraint(object,"exclusiveMinimum");if err!=nil{return Variable{},err};v.ExclusiveMaximum,err=numberConstraint(object,"exclusiveMaximum");if err!=nil{return Variable{},err};v.MultipleOf,err=numberConstraint(object,"multipleOf");if err!=nil{return Variable{},err};if raw,ok:=object["enum"];ok{if err:=decodeAny(raw,&v.Enum);err!=nil{return Variable{},fmt.Errorf("%s enum is invalid",name)}};if raw,ok:=object["default"];ok{if err:=decodeAny(raw,&v.Default);err!=nil||!matchesType(v.Default,typ){return Variable{},fmt.Errorf("%s default is incompatible",name)};v.HasDefault=true};if v.Secret&&v.HasDefault{return Variable{},fmt.Errorf("%s secret variable cannot have a default",name)};return v,nil}
func decodeAny(raw json.RawMessage,target any)error{d:=json.NewDecoder(bytes.NewReader(raw));d.UseNumber();return d.Decode(target)}
func matchesType(value any,typ string)bool{switch typ{case "string":_,ok:=value.(string);return ok;case "boolean":_,ok:=value.(bool);return ok;case "integer":n,ok:=value.(json.Number);return ok&&integerRE.MatchString(n.String());case "number":_,ok:=value.(json.Number);return ok};return false}
func intConstraint(m map[string]json.RawMessage,key string)(*int,error){raw,ok:=m[key];if !ok{return nil,nil};var value int;if err:=json.Unmarshal(raw,&value);err!=nil||value<0{return nil,fmt.Errorf("%s must be a non-negative integer",key)};return &value,nil}
func numberConstraint(m map[string]json.RawMessage,key string)(*float64,error){raw,ok:=m[key];if !ok{return nil,nil};var value float64;if err:=json.Unmarshal(raw,&value);err!=nil||math.IsNaN(value)||math.IsInf(value,0){return nil,fmt.Errorf("%s must be finite",key)};return &value,nil}

func loadEnvironment(path string)(map[string]string,error){if path==""{values:=map[string]string{};for _,entry:=range os.Environ(){key,value,ok:=strings.Cut(entry,"=");if !ok{return nil,errors.New("invalid process environment entry")};values[key]=value};return values,nil};file,err:=os.Open(path);if err!=nil{return nil,fmt.Errorf("open environment file: %w",err)};defer file.Close();values:=map[string]string{};scanner:=bufio.NewScanner(file);scanner.Buffer(make([]byte,1024),1024*1024);lineNumber:=0;for scanner.Scan(){lineNumber++;line:=strings.TrimSuffix(scanner.Text(),"\r");trimmed:=strings.TrimSpace(line);if trimmed==""||strings.HasPrefix(trimmed,"#"){continue};key,value,ok:=strings.Cut(line,"=");if !ok||key==""||strings.TrimSpace(key)!=key{return nil,fmt.Errorf("environment file line %d is malformed",lineNumber)};if _,ok:=values[key];ok{return nil,fmt.Errorf("environment file line %d duplicates variable",lineNumber)};if strings.Contains(value,"$"){return nil,fmt.Errorf("environment file line %d uses unsupported interpolation",lineNumber)};if len(value)>=2&&(value[0]=='\''&&value[len(value)-1]=='\''||value[0]=='\"'&&value[len(value)-1]=='\"'){value=value[1:len(value)-1]};values[key]=value};return values,scanner.Err()}

func validate(c Contract,env map[string]string)[]Diagnostic{names:=make([]string,0,len(c.Variables));for name:=range c.Variables{names=append(names,name)};sort.Strings(names);out:=[]Diagnostic{};for _,name:=range names{v:=c.Variables[name];raw,ok:=env[name];if !ok{if v.Required{out=append(out,Diagnostic{"error","ENV_MISSING",name,"Required variable is not set."})};continue};if raw==""&&v.Required{out=append(out,Diagnostic{"error","ENV_EMPTY",name,"Required variable is set but empty."});continue};bad:=v.Type=="integer"&&!integerRE.MatchString(raw)||v.Type=="number"&&!numberRE.MatchString(raw)||v.Type=="boolean"&&!strings.EqualFold(raw,"true")&&!strings.EqualFold(raw,"false");if bad{out=append(out,Diagnostic{"error","ENV_TYPE_MISMATCH",name,"Value does not match the declared type."});continue};if v.Pattern!=nil&&!v.Pattern.MatchString(raw){out=append(out,Diagnostic{"error","ENV_PATTERN_MISMATCH",name,"Value does not match the declared pattern."})};if v.MinLength!=nil||v.MaxLength!=nil{n:=utf8.RuneCountInString(raw);if v.MinLength!=nil&&n<*v.MinLength||v.MaxLength!=nil&&n>*v.MaxLength{out=append(out,Diagnostic{"error","ENV_PATTERN_MISMATCH",name,"String length is outside the declared bounds."})}};if v.Format=="email"{a,e:=mail.ParseAddress(raw);if e!=nil||a.Address!=raw{out=append(out,Diagnostic{"error","ENV_INVALID_FORMAT",name,"Value does not match the declared format."})}};if v.Format=="uri"{u,e:=url.ParseRequestURI(raw);if e!=nil||u.Scheme==""{out=append(out,Diagnostic{"error","ENV_INVALID_FORMAT",name,"Value does not match the declared format."})}};if v.Type=="integer"||v.Type=="number"{n,_:=strconv.ParseFloat(raw,64);bad:=v.Minimum!=nil&&n<*v.Minimum||v.Maximum!=nil&&n>*v.Maximum||v.ExclusiveMinimum!=nil&&n<=*v.ExclusiveMinimum||v.ExclusiveMaximum!=nil&&n>=*v.ExclusiveMaximum;if v.MultipleOf!=nil&&math.Abs(n/ *v.MultipleOf-math.Round(n/ *v.MultipleOf))>1e-9{bad=true};if bad{out=append(out,Diagnostic{"error","ENV_NUMBER_OUT_OF_RANGE",name,"Numeric value is outside the declared bounds."})}}};for name:=range env{if _,ok:=c.Variables[name];!ok{out=append(out,Diagnostic{"warning","ENV_UNKNOWN",name,"Variable is not declared in the contract."})}};sort.Slice(out,func(i,j int)bool{if out[i].Variable!=out[j].Variable{return out[i].Variable<out[j].Variable};return out[i].Code<out[j].Code});return out}

func checkCommand(args []string,out,errOut io.Writer)int{contractPath,envPath,jsonOutput,err:=parseOptions(args);if err!=nil{return failure(errOut,false,"SOURCE_INVALID",err.Error())};contract,err:=loadContract(contractPath);if err!=nil{return failure(errOut,jsonOutput,"CONTRACT_INVALID",err.Error())};env,err:=loadEnvironment(envPath);if err!=nil{return failure(errOut,jsonOutput,"ENV_FILE_INVALID",err.Error())};diagnostics:=validate(contract,env);valid:=true;for _,item:=range diagnostics{if item.Severity=="error"{valid=false}};if jsonOutput{_ = json.NewEncoder(out).Encode(result{valid,diagnostics})}else{if valid{fmt.Fprintln(out,"Environment is valid")}else{fmt.Fprintln(out,"Environment validation failed")};for _,item:=range diagnostics{marker:="✗";if item.Severity=="warning"{marker="⚠"};fmt.Fprintf(out,"%s %s\n  %s %s\n  %s\n",marker,item.Variable,strings.ToUpper(item.Severity),item.Code,item.Message)}};if !valid{return 1};return 0}
func parseOptions(args []string)(string,string,bool,error){contractPath,envPath:="envdoctor.schema.json","";jsonOutput:=false;environment:=false;for i:=0;i<len(args);i++{switch args[i]{case "--json":jsonOutput=true;case "--environment":environment=true;case "--contract","--env-file":if i+1>=len(args){return "","",false,errors.New("option requires a path")};i++;if args[i-1]=="--contract"{contractPath=args[i]}else{envPath=args[i]};default:return "","",false,fmt.Errorf("unknown option %q",args[i])}};if environment&&envPath!=""{return "","",false,errors.New("choose either --env-file or --environment")};return contractPath,envPath,jsonOutput,nil}
func initCommand(args []string,out,errOut io.Writer)int{path:="envdoctor.schema.json";if len(args)==2&&args[0]=="--contract"{path=args[1]};if _,err:=os.Stat(path);err==nil{return failure(errOut,false,"SOURCE_INVALID","contract already exists; refusing to overwrite")};data:=[]byte("{\n  \"$schema\": \""+schemaURL+"\",\n  \"x-envdoctor-version\": \"1\",\n  \"type\": \"object\",\n  \"properties\": {},\n  \"required\": []\n}\n");if err:=os.WriteFile(path,data,0644);err!=nil{return failure(errOut,false,"SOURCE_INVALID","cannot create contract")};fmt.Fprintf(out,"Created %s\n",path);return 0}
func generateCommand(args []string,out,errOut io.Writer)int{contractPath,outputPath:="envdoctor.schema.json",".env.example";force:=false;for i:=0;i<len(args);i++{switch args[i]{case "--force":force=true;case "--contract","--output":if i+1>=len(args){return usageError(errOut)};i++;if args[i-1]=="--contract"{contractPath=args[i]}else{outputPath=args[i]};default:return usageError(errOut)}};contract,err:=loadContract(contractPath);if err!=nil{return failure(errOut,false,"CONTRACT_INVALID",err.Error())};if _,err:=os.Stat(outputPath);err==nil&&!force{return failure(errOut,false,"SOURCE_INVALID","output exists; use --force to replace it")};names:=make([]string,0,len(contract.Variables));for name:=range contract.Variables{names=append(names,name)};sort.Strings(names);var builder strings.Builder;for _,name:=range names{v:=contract.Variables[name];if v.Description!=""{fmt.Fprintf(&builder,"# %s\n",v.Description)};value:="";if v.HasDefault&&!v.Secret{value=fmt.Sprint(v.Default)};fmt.Fprintf(&builder,"%s=%s\n",name,value)};if err:=os.WriteFile(outputPath,[]byte(builder.String()),0644);err!=nil{return failure(errOut,false,"SOURCE_INVALID","cannot write example")};fmt.Fprintf(out,"Wrote %s\n",outputPath);return 0}
func failure(w io.Writer,jsonOutput bool,code,message string)int{item:=Diagnostic{"error",code,"",message};if jsonOutput{_ = json.NewEncoder(w).Encode(result{false,[]Diagnostic{item}})}else{fmt.Fprintf(w,"ERROR %s: %s\n",code,message)};return 2}
func usageError(w io.Writer)int{fmt.Fprintln(w,"envdoctor: invalid command or option");fmt.Fprintln(w,"Run 'envdoctor --help' for usage.");return 2}
